### ISSUE TITLE
Edit Redress script

### ISSUE THREAD

**Issue by BR-Murdock** [BR-Murdock/ACE3Wasteland_EscobarsLegacy.Altis#17]
Make it work for 3 sides

**Comment by BR-Murdock** [comment]
Made some changes to different files to Support three factions.
fn_Redress.sqf has some medical stuff to be changed to ACE items for the Medics

**Comment by BR-Murdock** [comment]
Added the addtoinit file with instructions on installing the script.
Other files are mainly done, if you can, check them please, @zimm794 @GriffinZS 

@GriffinZS 
redressInit.sqf has to be edited at lines 40 to 62 to have the right gear/uniform/stuff for the different sides.

**Comment by GriffinZS** [comment]
Please give the edited sqf, not instructions, how or where to change. 
And it would be nice, if **u** would edit the named init and description, too.

So we could just copy/paste these folders and check them. Otherwise we would maybe mark a mistake  where we just made this mistake while implementing.

Thx ;)

**Comment by BR-Murdock** [comment]
I can edit the gear, but you would have to give me the uniform and other class names again first ^^
But I added the lines in description and init. Root init though. If it is not working, the init line has to go to the Server/init.sqf

**Comment by GriffinZS** [comment]
**BLUEFOR/DEA**

//Gear classes names go below!
//-----------------------------
JSHK_weaponArr = ["arifle_MX_Hamr_pointer_F","arifle_MXC_Holo_pointer_F","arifle_MXM_Hamr_pointer_F","arifle_MXC_ACO_pointer_F","srifle_EBR_MRCO_LP_BI_F"];
JSHK_uniformArr = ["TRYK_shirts_BLK_PAD","TRYK_shirts_BLK_PAD_BK","TRYK_shirts_PAD_YEL","TRYK_T_BLK_PAD"];
JSHK_vestArr = ["TRYK_V_ArmorVest_Delta", "TRYK_V_ArmorVest_HRT_OD", "TRYK_V_tacv1_P_BK"];
JSHK_headArr = ["TRYK_H_headsetcap_blk","TRYK_H_headsetcap_blk_Glasses","TRYK_H_headsetcap_od_Glasses","TRYK_R_CAP_BLK","TRYK_r_cap_blk_Glasses"];
JSHK_goggleArr = ["TRYK_Beard_BK","TRYK_Beard_Gr2","G_Aviator","G_Balaclava_blk","G_Lowprofile","G_Balaclava_combat","G_Spectacles_Tinted"];
JSHK_backpackArr = ["TRYK_B_AssaultPack_MARPAT_Wood","TRYK_B_Kitbag_blk","TRYK_B_Medbag","TRYK_B_tube_cyt","TRYK_B_Alicepack","TRYK_B_BAF_BAG_CYT"];
//-----------------------------

**OPFOR/Los Pepes**

//Gear classes names go below!
//-----------------------------
JSHK_weaponArr = ["arifle_Katiba_C_ACO_pointer_F","arifle_Katiba_ARCO_F","arifle_Katiba_GL_ACO_F","arifle_Mk20_GL_MRCO_pointer_F","srifle_DMR_03_woodland_F","MMG_01_hex_ARCO_LP_F"];
JSHK_uniformArr = ["TRYK_U_B_BLK","TRYK_U_B_BLK_OD","TRYK_U_B_BLK_OD_Tshirt","TRYK_U_B_BLKBLK_R_CombatUniform","TRYK_U_B_BLKOCP_R_CombatUniformTshirt"];
JSHK_vestArr = ["TRYK_LOC_AK_chestrig_OD", "TRYK_V_Bulletproof_BLK", "TRYK_V_harnes_blk_L","TRYK_V_IOTV_BLK","TRYK_V_PlateCarrier_blk_L"];
JSHK_headArr = ["TRYK_H_Bandana_wig","TRYK_H_Bandana_wig_g","H_Cap_blk","H_Cap_blk_CMMG","H_Cap_blk_ION","H_Beret_blk","H_BandMask_blk"];
JSHK_goggleArr = ["G_Bandanna_sport","G_Bandanna_tan","G_Balaclava_blk","G_Bandanna_beast","G_Bandanna_blk","G_Bandanna_khk","G_Bandanna_oli"];
JSHK_backpackArr = ["TRYK_B_tube_blk","TRYK_B_Medbag_BK","TRYK_B_Kitbag_blk","TRYK_B_Carryall_blk","B_AssaultPack_blk","B_FieldPack_blk"];
//-----------------------------

**Indy/Medellin**

//Gear classes names go below!
//-----------------------------
JSHK_weaponArr = ["srifle_EBR_ARCO_pointer_F","arifle_Katiba_ARCO_F","arifle_Mk20_Holo_F","arifle_MX_Black_Hamr_pointer_F","hgun_PDW2000_Holo_snds_F","srifle_DMR_03_ARCO_F","MMG_02_sand_RCO_LP_F"];
JSHK_uniformArr = ["TRYK_U_B_RED_T_BR","TRYK_U_denim_hood_3c","TRYK_U_denim_hood_blk","TRYK_U_denim_hood_nc","TRYK_U_denim_hood_mc","TRYK_U_denim_jersey_blk"];
JSHK_vestArr = ["V_Rangemaster_belt", "V_BandollierB_khk", "V_BandollierB_oli","V_HarnessO_gry","TRYK_LOC_AK_chestrig_TAN"];
JSHK_headArr = ["H_Booniehat_khk","H_Cap_red","H_Cap_blk","H_Cap_blu"," H_Cap_oli","H_Cap_tan","H_Cap_grn"];
JSHK_goggleArr = ["G_Squares_Tinted","G_Spectacles_Tinted","G_Lady_Red","G_Lady_Blue","G_Sport_Checkered","G_Aviator","TRYK_Beard_BK"];
JSHK_backpackArr = ["B_AssaultPack_mcamo","B_AssaultPack_ocamo","B_Kitbag_cbr","TRYK_B_tube_od","TRYK_B_Medbag_ucp","TRYK_B_AssaultPack_UCP"];
//-----------------------------

**Comment by GriffinZS** [comment]
Cannot see any redress init sqf. Master or Dev?

**Comment by GMan-One** [comment]
So wie Murdock es jetzt umgesetzt hat. Hab ich mir den ganzen Vormittag den Kopf zerbrochen.
Und am schluss hatte ich mir gesagt setzte es in den case.
Und was lese ich was Murdock gemacht hat? Er hat es in den case gesetzt.
1A
Nice Job Murdock

**Comment by BR-Murdock** [comment]
added the class names provided by Griffin.
_closed till further notice_
