### ISSUE TITLE
Check Store files

### ISSUE THREAD

**Issue by BR-Murdock** [BR-Murdock/ACE3Wasteland_EscobarsLegacy.Altis#6]
One big to do.
Check the Positions
Check the available Items and configure them.
Delete gunned vehicles
Add tryk and ace and tfar Items
Make some Items only available for a specific side (West,east,guer)
Some more

**Comment by BR-Murdock** [comment]
Disabled the Titan AT.
Removed gunned vehicles. I left the drones in for some fun

**Comment by GriffinZS** [comment]
Question: base building stuf .. I would prefer funitures etc. Beside walls, fences etc.

**Comment by BR-Murdock** [comment]
@GriffinZS Sure, why not. Maybe we can divide it somehow between base building and furniture type objects and delete some unwanted or add some more wanted buildings (you remember the hut and Wood-houses we tried on esseker once?)

**Comment by GriffinZS** [comment]
Everything except of bulding parts added. 
Closed here. Drugs (pickable and for usage) & building parts (load-placeable) should be new issue ..
